[build]
    base    = "/"
    publish = "build"
    command = "npm run build"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
    from = "/*"
    to = "/"
    status = 200
